In [9]:
import numpy as np
import os
import pandas as pd

In [3]:
base_path = '/mnt/disk1/heonseok/MPMLD/data/location'
dataset = np.load(os.path.join(base_path, 'data_complete.npz'))

In [7]:
# print(dataset)
x_data=dataset['x'][:,:]
y_data=dataset['y'][:]

print(x_data)
print(x_data.shape)
print(y_data)
print(y_data.shape)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
(5010, 446)
[13 11  3 ... 10 20  4]
(5010,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

In [10]:
df = pd.DataFrame(x_data)
print(df.describe())

               0            1            2            3            4    \
count  5010.000000  5010.000000  5010.000000  5010.000000  5010.000000
mean      0.058283     0.178044     0.047904     0.537325     0.092814
std       0.234302     0.382588     0.213585     0.498655     0.290201
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     1.000000     0.000000
75%       0.000000     0.000000     0.000000     1.000000     0.000000
max       1.000000     1.000000     1.000000     1.000000     1.000000

               5            6            7            8            9    ...  \
count  5010.000000  5010.000000  5010.000000  5010.000000  5010.000000  ...
mean      0.107385     0.030938     0.058283     0.161277     0.064271  ...
std       0.309633     0.173167     0.234302     0.367823     0.245260  ...
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...

               436          437          438          439          440  \
count  5010.000000  5010.000000  5010.000000  5010.000000  5010.000000
mean      0.036527     0.049501     0.043313     0.049301     0.062076
std       0.187616     0.216933     0.203582     0.216518     0.241317
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.000000     0.000000     0.000000     0.000000     0.000000
50%       0.000000     0.000000     0.000000     0.000000     0.000000
75%       0.000000     0.000000     0.000000     0.000000     0.000000
max       1.000000     1.000000     1.000000     1.000000     1.000000

               441         442          443          444          445
count  5010.000000  5010.00000  5010.000000  5010.000000  5010.000000
mean      0.047505     0.20519     0.067864     0.124551     0.057485
std       0.212738     0.40388     0.251538     0.330242     0.232790
min       0.000000     0.00000     0.000000     0.000000     0.000000
25%       0.000000     0.00000     0.000000     0.000000     0.000000
50%       0.000000     0.00000     0.000000     0.000000     0.000000
75%       0.000000     0.00000     0.000000     0.000000     0.000000
max       1.000000     1.00000     1.000000     1.000000     1.000000

[8 rows x 446 columns]

In [12]:
print(np.unique(y_data))
print(len(np.unique(y_data)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
30

In [13]:
y_data = y_data - 1
print(np.unique(y_data))
print(len(np.unique(y_data)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
30

In [15]:
y_data_small = y_data[0:1000]
print(np.unique(y_data_small))
print(len(np.unique(y_data_small)))
print(y_data_small)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
30
[12 10  2  8  7  2 19 10 18 26 12 28  3 29 25 13 10  0 22 20  5 10 15 27
  7  4  9 19 16 20  7 24 18 29 11 25 22 17  1 25 18  2 23 16 19  0  4 19
 17 12 29 27 14 12  8 28 14 22  2  6 11 27 14 23 16  3 12 29  8 19  3 26
 12 18 19 27 29 18  7  0 14 21 19 14 22 14 13 10  0 29 29 22 15 26 20  1
 12 10  3 27  5 26  7  0 19  1 13 22 23 27 29  7 23 29 13 13  8 20  1  1
 28  3 19  7 11 19  8  3  6 23 23  2 27 28  7 20 23 20 18 24 22 28 28  1
 20 28  2 11 14 29 26  2  0  2  7 11 21 17 19  7  5 13 25  8 18 20 25 20
 13  7 20 10  9 23  7 24 21  4  0 19  9 18 11  6 16 20 25  2  9 12 26 12
  3 22 14  2 27  2 14 23 22 15 10  5 16 19  8  8  7 20 18  7 20  7 12 19
  4 18 26 26 28  4 22 29  9 10 13 28 19  4 19 20  9  0  0 26 28 28 19 10
 27  8 16 29 25 21  9  4 12  3  6 14  6 25 19 17 27 19 12  7 14  5  7 26
 28 22 27 22 20 16 25 21  9 14 21 14 23 19 27 22  5 26 19 29  6 15 11  2
  7  2 23 15 25 10 27 19 14 27 11 21  7 15 22 26  9 17  1  5 12 19 16 28
 29 10 12 23  0 25  8  7 17 13 22 19 14 17 17 28  1 12 10 29  0 10 22  5
 14 20  6 26 27  5 14 21 16 19  0  6  5 14 26  9 22 10 11 16 10 29  2 19
 29 26  7 17 28 18 13  0  3 14  3 16 23  0  7 21 29 27 19 14  9 20  2  0
  7 24  9  2  0 21  7 20  1 29  3  5 11  7  6 10 19 21 29 16 25  6 29  5
 19 29  9 18  4  3  3 10 22 26 19 18 23 29  5  3 13 25  9  2 23 22 14 11
  0 25  4 15  7  2 20 20 28  8  1 14 13 18  0  7 29 27  9 21 22  5  6 20
 13  9 11  0 16  7  9 27 22 25  6 15 11 18  5  3  6  6  5 20 20 20 12 14
 25  7  9  7  9 23 16 19  7 17 19 13  7 12 11  8  6 20 10 26  9  4 14 18
 29  2 21 19 18  2  7 21  7  2 14  0 12  7 27 10  5 12 11 19 26 26 19 17
 10 16 26 15 15  7 14 10 26  1  5 19 26 19 13 13 18 21  9  9  7 28  4 14
 26  9 26 18  7 21 23  2 24 23  5  6 10 13  5 18 19 27  7 27  3 25 27 14
  7 10 22  2 21 20  1 21 28 24 22  3  1  2 20  1 20 25  3  7 15 17 11  2
 19  2 24 28 26 28  4 14 11  5 27 29 14 23 20  5  5 24 17 23  5  1 24  7
  3 10 18 11 13 27 12  3  2  0 17 16 24  9 16 27 23 23  7 28 16 26 10 29
 11 23 29 16 14 16  1  7  0 22  9 12  9  0 15  7 13 27 21 19  8  9 15 29
  1 19 11  8 16  2 14 15  5  4 27 14  7 29 13  3  5 18 12 11  4 19 23  8
 18  6 23 28 22 17 19 17 16 19 18  7 22 20 18 26 17 26  9  4 23 27 28 10
 24  7 28  7  5 19 26  5 11 29 17  7 10 29  6 24 12 17  8 23  4  7 20 23
 18 20  9 17 20 13 23 19  9 27 14  5 12  5  1  3  7 13 20 18  6  7 19  3
 23 13 12 26 26 25  8 16 14 24 16 20 13 11 15  9 11 21  7 26 20 14  8 21
 15 19 17  7 19 13 20 20  7  4 14 12 20  8  7 24  8  0 10 17 16 19 14  9
  7 20  8  2  4 29 25  2 14  3  8 14 16 27  5  5 11  1 17 10 19 13  9 14
 23 13 15 17  7 20  5 16 11 16  1  0 16 11  3  9 24 28 16 23  2 25  1  6
 26 12 15 24 11 20 19 21 12  8  9  1 22  1  9  5  4 20 22 19 20 14 28 15
 20 20 10  5 28 24 15  0  9 12 18 28 11  7 18 14 19  9 16 10  7 21 23 14
  1 24 27 20 17  9 24 23  7 17 23  9 23 17 11 18 12 27 16  9  6 17  7  5
  1  5 24  3  1  1  7 20  5  8 27 27  5  7 10 21 23  2 14  3  9 23 17  2
  9  3  7 28 17  4  2 21  7  2  9 18 18 19  7 21 16 25 21  5 26  7 15  3
 28  7 22 21 27  6 10 14  7 22  1 13  2 25 14 18]

In [17]:
for i in range(len(np.unique(y_data))):
    print(i, np.sum(y_data == i))

0 169
1 178
2 147
3 155
4 97
5 182
6 120
7 308
8 145
9 210
10 189
11 184
12 141
13 122
14 229
15 110
16 176
17 128
18 180
19 254
20 228
21 117
22 158
23 170
24 139
25 139
26 155
27 152
28 149
29 179

In [18]:

for i in range(len(np.unique(y_data_small))):
    print(i, np.sum(y_data_small == i))

0 26
1 28
2 36
3 29
4 20
5 40
6 22
7 71
8 24
9 44
10 34
11 30
12 30
13 28
14 47
15 21
16 33
17 30
18 33
19 55
20 48
21 28
22 30
23 38
24 20
25 23
26 34
27 35
28 30
29 33